In [125]:
import numpy as np 
import tensorflow as tf
import ker

ModuleNotFoundError: No module named 'tensorflow.keras'

In [113]:
w = tf.Variable(0.0, dtype=tf.float32)
# J = tf.add(tf.subtract(tf.pow(w,2),tf.multiply(w,10)), 25)
# J = w**2 - 10*w + 25
x = tf.placeholder(tf.float32,[3])
coefficients = np.array([1.,-10.,25.])
J = x[0]*w**2 + x[1]*w + x[2]
train = tf.train.GradientDescentOptimizer(0.1).minimize(J)

In [114]:
init = tf.global_variables_initializer()

In [115]:
session = tf.Session()
session.run(init)
print(session.run(w))
print(session.run(J, feed_dict={x:coefficients}))

0.0
25.0


In [116]:
for i in range(1000):
    session.run(train, feed_dict={x:coefficients})
print(session.run(w))
print(session.run(J, feed_dict={x:coefficients}))

5.0
-1.90735e-06


In [117]:
session.close()

In [134]:
a = np.random.rand(2,3,4)
print(a)

[[[ 0.12389456  0.24978085  0.58817193  0.09856927]
  [ 0.3584317   0.60417066  0.10433987  0.64132859]
  [ 0.50628437  0.81510713  0.54633998  0.31642604]]

 [[ 0.93357038  0.70070661  0.09339233  0.70794546]
  [ 0.33053236  0.07701491  0.68450629  0.38423922]
  [ 0.5815188   0.96924296  0.67207158  0.07447572]]]


In [137]:
np.max(a,axis=0)

array([[ 0.93357038,  0.70070661,  0.58817193,  0.70794546],
       [ 0.3584317 ,  0.60417066,  0.68450629,  0.64132859],
       [ 0.5815188 ,  0.96924296,  0.67207158,  0.31642604]])

In [138]:
np.max(a,axis=1)

array([[ 0.50628437,  0.81510713,  0.58817193,  0.64132859],
       [ 0.93357038,  0.96924296,  0.68450629,  0.70794546]])

In [139]:
np.max(a,axis=2)

array([[ 0.58817193,  0.64132859,  0.81510713],
       [ 0.93357038,  0.68450629,  0.96924296]])

In [140]:
np.max(a,axis=-1)

array([[ 0.58817193,  0.64132859,  0.81510713],
       [ 0.93357038,  0.68450629,  0.96924296]])

In [141]:
box1 = (2, 1, 4, 3)
box2 = (1, 2, 3, 4)

In [144]:
box1.1

SyntaxError: invalid syntax (<ipython-input-144-abdade25bd46>, line 1)

In [146]:
a_G = tf.random_normal([1, 4, 4, 3], mean=1, stddev=4)

In [147]:
print(a_G)

Tensor("random_normal:0", shape=(1, 4, 4, 3), dtype=float32)


In [154]:
with tf.Session() as sess:
    print(sess.run(a_G))
    print("#######")
    print(sess.run(tf.reshape(a_G,(1,3,16))))
    print("#######")
    print(sess.run(tf.reshape(a_G,(1,16,3))))

[[[[-1.28487158 -4.65712214 -3.69754744]
   [ 3.49677706  5.49320221  6.21671009]
   [-0.92942035  1.1047051   1.95406258]
   [-1.54450583  2.62630558 -0.93994105]]

  [[ 3.00776505 -2.83131003  4.024436  ]
   [-0.33929348 -0.9525578   4.21731186]
   [-0.58576965 -4.51304436  4.06365538]
   [ 4.74829578 -0.42018163  5.6671958 ]]

  [[ 0.60779279  2.57430506 -0.46098471]
   [ 7.25215483 -4.41498947 -2.32243252]
   [ 2.21872854 -5.24966097 -6.4372735 ]
   [ 3.66865444 -0.5479902  -1.90269279]]

  [[ 4.27260971 -3.46149015  0.86021906]
   [ 3.45513725 -0.10285735 -2.67844105]
   [-1.19517398  9.44965744 -3.66468573]
   [-3.00457573  3.12048006  2.03534436]]]]
#######
[[[ -0.19513428   1.34603751   0.94837159  -5.24046659   0.12314409
     1.18385112  -0.51064372   0.20193505  -1.48246074  -2.61157441
    -5.22344351   5.60201311  -6.65609407  -2.33237743  -0.52891934
     4.03483772]
  [ 10.10686398  -2.71461678   1.30271626   8.57744217  -0.45530272
    -6.2827673    5.24723434   4.99404